name: flutter_redrocket_test_task
description: "Test task for Red rocket"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  get_it: ^8.2.0
  injectable: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - env/
