name: flutter_redrocket_test_task
description: "Test task for Red rocket"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  injectable: ^2.5.1
  json_annotation: ^4.9.0
  logger: ^2.6.1
  retrofit: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  retrofit_generator: ^10.0.4

flutter:
  uses-material-design: true
  assets:
    - env/
